version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/greenstate?schema=public
    depends_on:
      - database
    ports:
      - 3000:3000
    command: yarn start

  database:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=greenstate
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5435:5432

volumes:
  db_data:
